In [2]:
# Q1

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ elements:", type(list_[0]))
print("Data type of array_list elements:", array_list.dtype)

# This confirms that while list_ is a standard Python list containing str elements.
# Aarray_list is a NumPy array with a data type of Unicode strings (<U1).


Data type of list_ elements: <class 'str'>
Data type of array_list elements: <U1


In [3]:
# Q2

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


print("Data types of elements in list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")

print("\nData types of elements in array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")

# The elements in list_ are of type str (Python string).

# The elements in array_list are of type numpy.str_ (NumPy string type).


Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


In [4]:
# Q3

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(f"Element: {element}, Type: {type(element)}")

print("\nData types of elements in array_list:")
for element in array_list:
    print(f"Element: {element}, Type: {type(element)}")

# list_ elements remain str (Python strings).

# array_list elements are now converted to numpy.int64 (or numpy.int32 on some systems), which are integers.




Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.int64'>
Element: 2, Type: <class 'numpy.int64'>
Element: 3, Type: <class 'numpy.int64'>
Element: 4, Type: <class 'numpy.int64'>
Element: 5, Type: <class 'numpy.int64'>


In [5]:
# Q4

import numpy as np

num_array = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
# Q5

import numpy as np

zero_matrix = np.zeros((3, 3))

print("3x3 Zero Matrix:\n", zero_matrix)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Q6

import numpy as np

identity_matrix = np.eye(5)

print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
